"""Incident artifact config — extracted from RemoteIncident OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

INCIDENT_CONFIG = ArtifactConfig(
    artifact_type="incident",
    workspace_type="product",
    search_endpoint="projects/{product_id}/incidents/search",
    single_endpoint="projects/{product_id}/incidents/{artifact_id}",
    description=("Incidents (bugs, issues, defects) tracked in a Spira product."),
    # Normalised field mappings
    status_field="IncidentStatusId",
    owner_field="OwnerId",
    priority_field="PriorityId",
    release_field="ResolvedReleaseId",
    type_field="IncidentTypeId",
    summary_fields=[
        "IncidentId",
        "Name",
        "IncidentTypeName",
        "IncidentStatusName",
        "PriorityName",
        "SeverityName",
        "OwnerName",
        "ResolvedReleaseVersionNumber",
    ],
    # all_fields: LLM-visible fields from RemoteIncident schema
    all_fields=[
        "ActualEffort",
        "ClosedDate",
        "CompletionPercent",
        "ComponentIds",
        "CreationDate",
        "Description",
        "DetectedReleaseId",
        "DetectedReleaseVersionNumber",
        "EndDate",
        "EstimatedEffort",
        "IncidentId",
        "IncidentStatusId",
        "IncidentStatusName",
        "IncidentStatusOpenStatus",
        "IncidentTypeId",
        "IncidentTypeName",
        "LastUpdateDate",
        "Name",
        "OpenerId",
        "OpenerName",
        "OwnerId",
        "OwnerName",
        "PriorityId",
        "PriorityName",
        "ProjectedEffort",
        "ProjectId",
        "ProjectName",
        "RemainingEffort",
        "ResolvedReleaseId",
        "ResolvedReleaseVersionNumber",
        "SeverityId",
        "SeverityName",
        "StartDate",
        "Tags",
        "VerifiedReleaseId",
        "VerifiedReleaseVersionNumber",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "ConcurrencyDate",
        "CustomProperties",
        "DetectedBuildId",
        "DetectedBuildName",
        "DetectedReleaseGuid",
        "FixedBuildId",
        "FixedBuildName",
        "Guid",
        "IsAttachments",
        "OpenerGuid",
        "OwnerGuid",
        "ProjectGuid",
        "ResolvedReleaseGuid",
        "TestRunStepIds",
        "VerifiedReleaseGuid",
    ],
    supports_server_search=True,
    mywork_endpoint="incidents",
    search_query_params={
        "row_start": "start_row",
        "row_count": "number_rows",
        "sort_by": "sort_by",
    },
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
)
