"""Release artifact config — extracted from RemoteRelease OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

RELEASE_CONFIG = ArtifactConfig(
    artifact_type="release",
    workspace_type="product",
    search_endpoint="projects/{product_id}/releases/search",
    single_endpoint="projects/{product_id}/releases/{artifact_id}",
    description="Releases and iterations tracked in a Spira product.",
    # Normalised field mappings
    status_field="ReleaseStatusId",
    owner_field="OwnerId",
    priority_field=None,
    release_field=None,
    type_field="ReleaseTypeId",
    summary_fields=[
        "Name",
        "OwnerName",
        "PercentComplete",
        "ReleaseId",
        "ReleaseStatusName",
        "ReleaseTypeName",
        "VersionNumber",
    ],
    # all_fields: LLM-visible fields from RemoteRelease schema
    all_fields=[
        "Active",
        "AvailableEffort",
        "CountBlocked",
        "CountCaution",
        "CountFailed",
        "CountNotApplicable",
        "CountNotRun",
        "CountPassed",
        "CreationDate",
        "CreatorId",
        "CreatorName",
        "DaysNonWorking",
        "Description",
        "EndDate",
        "IndentLevel",
        "LastUpdateDate",
        "Name",
        "OwnerId",
        "OwnerName",
        "PercentComplete",
        "PlannedEffort",
        "ProjectId",
        "ReleaseId",
        "ReleaseStatusId",
        "ReleaseStatusName",
        "ReleaseTypeId",
        "ReleaseTypeName",
        "RequirementCount",
        "RequirementPoints",
        "ResourceCount",
        "StartDate",
        "Summary",
        "Tags",
        "TaskActualEffort",
        "TaskCount",
        "TaskEstimatedEffort",
        "VersionNumber",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "ConcurrencyDate",
        "CreatorGuid",
        "CustomProperties",
        "FullName",
        "Guid",
        "IsAttachments",
        "OwnerGuid",
        "ProjectGuid",
    ],
    supports_server_search=True,
    mywork_endpoint=None,
    search_query_params={"row_start": "start_row", "row_count": "number_rows"},
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
)
