"""Requirement artifact config — extracted from RemoteRequirement OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

REQUIREMENT_CONFIG = ArtifactConfig(
    artifact_type="requirement",
    workspace_type="product",
    search_endpoint="projects/{product_id}/requirements/search",
    single_endpoint="projects/{product_id}/requirements/{artifact_id}",
    description="Requirements tracked in a Spira product.",
    # Normalised field mappings
    status_field="StatusId",
    owner_field="OwnerId",
    priority_field="ImportanceId",
    release_field="ReleaseId",
    type_field="RequirementTypeId",
    summary_fields=[
        "ImportanceName",
        "Name",
        "OwnerName",
        "PercentComplete",
        "ReleaseVersionNumber",
        "RequirementId",
        "RequirementTypeName",
        "StatusName",
    ],
    # all_fields: LLM-visible fields from RemoteRequirement schema
    all_fields=[
        "AuthorId",
        "AuthorName",
        "ComponentId",
        "CoverageCountBlocked",
        "CoverageCountCaution",
        "CoverageCountFailed",
        "CoverageCountPassed",
        "CoverageCountTotal",
        "CreationDate",
        "Description",
        "EndDate",
        "EstimatePoints",
        "EstimatedEffort",
        "ImportanceId",
        "ImportanceName",
        "IsSuspect",
        "LastUpdateDate",
        "Name",
        "OwnerId",
        "OwnerName",
        "PercentComplete",
        "ProjectId",
        "ProjectName",
        "ReleaseId",
        "ReleaseVersionNumber",
        "RequirementId",
        "RequirementTypeId",
        "RequirementTypeName",
        "StartDate",
        "StatusId",
        "StatusName",
        "Summary",
        "Tags",
        "TaskActualEffort",
        "TaskCount",
        "TaskEstimatedEffort",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "AuthorGuid",
        "ConcurrencyDate",
        "CustomProperties",
        "GoalId",
        "Guid",
        "IsAttachments",
        "IndentLevel",
        "OwnerGuid",
        "ProjectGuid",
        "ReleaseGuid",
        "Steps",
    ],
    supports_server_search=True,
    mywork_endpoint="requirements",
    search_query_params={"row_start": "starting_row", "row_count": "number_of_rows"},
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
    includes=[
        "steps",
    ],
)
