"""Risk artifact config — extracted from RemoteRisk OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

RISK_CONFIG = ArtifactConfig(
    artifact_type="risk",
    workspace_type="product",
    search_endpoint="projects/{product_id}/risks/search",
    single_endpoint="projects/{product_id}/risks/{artifact_id}",
    description="Risks tracked in a Spira product.",
    # Normalised field mappings
    status_field="RiskStatusId",
    owner_field="OwnerId",
    priority_field="RiskProbabilityId",
    release_field="ReleaseId",
    type_field="RiskTypeId",
    summary_fields=[
        "Name",
        "OwnerName",
        "RiskId",
        "RiskProbabilityName",
        "RiskStatusName",
        "RiskTypeName",
    ],
    # all_fields: LLM-visible fields from RemoteRisk schema
    all_fields=[
        "ClosedDate",
        "ComponentId",
        "ComponentName",
        "CreationDate",
        "CreatorId",
        "CreatorName",
        "Description",
        "LastUpdateDate",
        "Name",
        "OwnerId",
        "OwnerName",
        "ProjectGroupId",
        "ProjectId",
        "ReleaseId",
        "ReleaseName",
        "ReleaseVersionNumber",
        "ReviewDate",
        "RiskDetectabilityId",
        "RiskDetectabilityName",
        "RiskExposure",
        "RiskId",
        "RiskImpactId",
        "RiskImpactName",
        "RiskProbabilityId",
        "RiskProbabilityName",
        "RiskStatusId",
        "RiskStatusName",
        "RiskTypeId",
        "RiskTypeName",
        "Tags",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "ConcurrencyDate",
        "CreatorGuid",
        "CustomProperties",
        "GoalId",
        "Guid",
        "IsAttachments",
        "IsDeleted",
        "OwnerGuid",
        "ProjectGuid",
        "ReleaseGuid",
    ],
    supports_server_search=True,
    mywork_endpoint=None,
    search_query_params={
        "row_start": "starting_row",
        "row_count": "number_of_rows",
        "sort_field": "sort_field",
        "sort_direction": "sort_direction",
    },
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
    includes=[
        "mitigations",
    ],
)
