"""Task artifact config — extracted from RemoteTask OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

TASK_CONFIG = ArtifactConfig(
    artifact_type="task",
    workspace_type="product",
    search_endpoint="projects/{product_id}/tasks/search",
    single_endpoint="projects/{product_id}/tasks/{artifact_id}",
    description="Tasks (work items, to-dos) tracked in a Spira product.",
    # Normalised field mappings
    status_field="TaskStatusId",
    owner_field="OwnerId",
    priority_field="TaskPriorityId",
    release_field="ReleaseId",
    type_field="TaskTypeId",
    summary_fields=[
        "TaskId",
        "Name",
        "TaskTypeName",
        "TaskStatusName",
        "TaskPriorityName",
        "OwnerName",
        "CompletionPercent",
        "ReleaseVersionNumber",
    ],
    # all_fields: LLM-visible fields from RemoteTask schema
    all_fields=[
        "ActualEffort",
        "CompletionPercent",
        "ComponentId",
        "CreationDate",
        "CreatorId",
        "Description",
        "EndDate",
        "EstimatedEffort",
        "LastUpdateDate",
        "Name",
        "OwnerId",
        "OwnerName",
        "ProjectId",
        "ProjectName",
        "ProjectedEffort",
        "ReleaseId",
        "ReleaseVersionNumber",
        "RemainingEffort",
        "RequirementId",
        "RequirementName",
        "StartDate",
        "Tags",
        "TaskFolderId",
        "TaskId",
        "TaskPriorityId",
        "TaskPriorityName",
        "TaskStatusId",
        "TaskStatusName",
        "TaskTypeId",
        "TaskTypeName",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "ConcurrencyDate",
        "CreatorGuid",
        "CustomProperties",
        "Guid",
        "IsAttachments",
        "OwnerGuid",
        "ProjectGuid",
        "ReleaseGuid",
        "RiskId",
    ],
    supports_server_search=True,
    mywork_endpoint="tasks",
    search_query_params={
        "row_start": "starting_row",
        "row_count": "number_of_rows",
        "sort_field": "sort_field",
        "sort_direction": "sort_direction",
    },
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
)
