"""Test Case artifact config — extracted from RemoteTestCase OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

TEST_CASE_CONFIG = ArtifactConfig(
    artifact_type="test_case",
    workspace_type="product",
    search_endpoint="projects/{product_id}/test-cases/search",
    single_endpoint="projects/{product_id}/test-cases/{artifact_id}",
    description="Test cases tracked in a Spira product.",
    # Normalised field mappings
    status_field="TestCaseStatusId",
    owner_field="OwnerId",
    priority_field="TestCasePriorityId",
    release_field=None,
    type_field="TestCaseTypeId",
    summary_fields=[
        "ExecutionStatusName",
        "Name",
        "OwnerName",
        "TestCaseId",
        "TestCasePriorityName",
        "TestCaseStatusName",
        "TestCaseTypeName",
    ],
    # all_fields: LLM-visible fields from RemoteTestCase schema
    all_fields=[
        "ActualDuration",
        "AuthorId",
        "AuthorName",
        "AutomationEngineId",
        "ComponentIds",
        "CreationDate",
        "Description",
        "EstimatedDuration",
        "ExecutionDate",
        "ExecutionStatusId",
        "ExecutionStatusName",
        "IsSuspect",
        "IsTestSteps",
        "LastUpdateDate",
        "Name",
        "OwnerId",
        "OwnerName",
        "ProjectId",
        "ProjectName",
        "Tags",
        "TestCaseFolderId",
        "TestCaseId",
        "TestCasePriorityId",
        "TestCasePriorityName",
        "TestCaseStatusId",
        "TestCaseStatusName",
        "TestCaseTypeId",
        "TestCaseTypeName",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "AuthorGuid",
        "AutomationAttachmentId",
        "ConcurrencyDate",
        "CustomProperties",
        "Guid",
        "IsAttachments",
        "OwnerGuid",
        "ProjectGuid",
        "TestSteps",
    ],
    supports_server_search=True,
    mywork_endpoint="test-cases",
    search_query_params={
        "row_start": "starting_row",
        "row_count": "number_of_rows",
        "sort_field": "sort_field",
        "sort_direction": "sort_direction",
        "release_id": "release_id",
    },
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
    includes=[
        "test_steps",
    ],
)
