"""Test Set artifact config — extracted from RemoteTestSet OpenAPI schema."""

from mcp_server_spira.models import ArtifactConfig

TEST_SET_CONFIG = ArtifactConfig(
    artifact_type="test_set",
    workspace_type="product",
    search_endpoint="projects/{product_id}/test-sets/search",
    single_endpoint="projects/{product_id}/test-sets/{artifact_id}",
    description="Test sets (collections of test cases) tracked in a Spira product.",
    # Normalised field mappings
    status_field="TestSetStatusId",
    owner_field="OwnerId",
    priority_field=None,
    release_field="ReleaseId",
    type_field=None,
    summary_fields=[
        "Name",
        "OwnerName",
        "TestSetId",
        "TestSetStatusName",
    ],
    # all_fields: LLM-visible fields from RemoteTestSet schema
    all_fields=[
        "ActualDuration",
        "AutomationHostId",
        "CountBlocked",
        "CountCaution",
        "CountFailed",
        "CountNotApplicable",
        "CountNotRun",
        "CountPassed",
        "CreationDate",
        "CreatorId",
        "CreatorName",
        "Description",
        "EstimatedDuration",
        "ExecutionDate",
        "LastUpdateDate",
        "Name",
        "OwnerId",
        "OwnerName",
        "PlannedDate",
        "ProjectId",
        "ProjectName",
        "RecurrenceId",
        "RecurrenceName",
        "ReleaseId",
        "ReleaseVersionNumber",
        "Tags",
        "TestConfigurationSetId",
        "TestRunTypeId",
        "TestSetFolderId",
        "TestSetId",
        "TestSetStatusId",
        "TestSetStatusName",
    ],
    # excluded_fields: valid OpenAPI fields hidden from LLM
    excluded_fields=[
        "ArtifactTypeId",
        "BuildExecuteTimeInterval",
        "ConcurrencyDate",
        "CreatorGuid",
        "CustomProperties",
        "DynamicQuery",
        "Guid",
        "IndentLevel",
        "IsAttachments",
        "IsAutoScheduled",
        "IsDynamic",
        "OwnerGuid",
        "ProjectGuid",
        "ReleaseGuid",
    ],
    supports_server_search=True,
    mywork_endpoint="test-sets",
    search_query_params={
        "row_start": "starting_row",
        "row_count": "number_of_rows",
        "release_id": "release_id",
        "sort_field": "sort_field",
        "sort_direction": "sort_direction",
    },
    default_sort_field="LastUpdateDate",
    default_sort_direction="desc",
)
